server:
  port: 9401
spring:
  profiles:
    active: dev
  application:
    name: auth-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    database: 0
    port: 6379
    host: localhost
    password: 123456
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/video?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: classpath:/com/leyu/video/persistence/mapper/xml/*Mapper.xml
  typeAliasesPackage: com.leyu.video.persistence.entity

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      springframework:
        security: debug
    com:
      leyu:
        video:
          persistence:
            mapper: debug
